version: '3.8'
services:
  movies:
    image: shivampatil0/paymovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: shivampatil0/paymovies:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: shivampatil0/recharge:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: shivampatil0/paydth:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3

